##################################################

# Run Mr Coxall's Super Linter against code base #

##################################################


---
name: Mr Coxall's Super Linter

on: [push, pull_request]


jobs:

  run-linters:

    name: Linters

    runs-on: ubuntu-latest


    steps:

      - name: Check out Git repository

        uses: actions/checkout@main



      - name: Run GitHub Super Linter

        uses: github/super-linter@main

        env:

          VALIDATE_ALL_CODEBASE: true
          
          VALIDATE_JAVASCRIPT_STANDARD: false

          DEFAULT_BRANCH: main

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
